### ISSUE TITLE
Exception when creating Angular project - reported on Discord by Haldun

### ISSUE THREAD

**Issue by mkamrani** [utopiops/utopiops#24]
name:  test
stack:  frontend
framework:  Angular
pm:  Yarn
uiFramework:  Bootstrap
testFramework:  Default
linting:  Prettier
====================
Creating the project test ...
yarn global v1.22.15
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "@angular/cli@13.3.4" with binaries:
      - ng
Done in 12.75s.
(node:32124) UnhandledPromiseRejectionWarning: Error: spawnSync ng ENOENT
    at Object.spawnSync (internal/child_process.js:1067:20)
    at spawnSync (child_process.js:602:24)
    at execFileSync (child_process.js:629:15)
    at createProject (F:\utopiops\cli\lib\angular.js:62:3)
    at module.exports (F:\utopiops\cli\lib\angular.js:51:3)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async module.exports (F:\utopiops\cli\lib\frontend.js:28:7)
    at async module.exports (F:\utopiops\cli\lib\git.js:36:7)
    at async module.exports (F:\utopiops\cli\lib\create.js:23:3)
    at async Command.<anonymous> (F:\utopiops\cli\bin\ks:15:23)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:32124) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:32124) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by mkamrani** [comment]
I couldn't reproduce it on my Mac with version 0.4.0, would be good to what's the OS of the machine error happened.
I'm suspecting this is a Window thing.

**Comment by TomCockram** [comment]
Yeah, this was performed on windows.

**Comment by mkamrani** [comment]
Sorry if this has taken some time, I'm using mac. I just started a Windows ec2 instance to be able to debug it.
